Add unit testing with Vitest
Daymannovaes/carousel-builder pull request #19
Opened 2024-11-04 23:56 UTC by gabrielttavares

- Tests component instantiation
- Verifies shadow DOM creation
- Checks for proper class assignment
- Validates style application

2024-11-21 15:55 UTC, Daymannovaes requested changes
- 2033 arquivos alterados
- node_modules foi commitado
- pasta dist foi commitada também
- aqruivo de vitest.config.js flutuando na pasta raiz

conserta ai pra nós please

2024-11-22 18:13 UTC, Daymannovaes requested changes
boa, tamo quase. Progrediu bastante, ta quase terminando o last mile.

2024-11-22 18:13 UTC, Daymannovaes commented on frontend/src/utils/create-list-items.ts
> +    displayText.appendChild(ul);
boa solução ao passar o `displayText` pra dentro do `createListItems`, mas isso trás alguns problemas. O primeiro é que o nome da função não descreve mais exatamente o que ela, uma vez que depois de "criar a lista de itens" você está dando um append do "displayText". Se fosse pro nome ser honesto, deveria ser algo como `createListItemsAndAppendInTextinput`.

Segundo problema é que essa função é mais complexa do que precisava. É muito melhor deixar a função ser de fato um "criador de lista de itens". Ou seja: ela **cria** e **retorna**, pra quem tiver chamando ela usar como quiser.

A assinatura do seu uso deveria ser assim:
```ts
// index.js
const listItems = createListItems(splitItems, { fontColor, backgroundColor });
displayText.append(listItems);
```

Isso vai facilitar a criação dos testes também.

2024-11-22 18:13 UTC, Daymannovaes commented on frontend/tests/initialize-color-picker.test.ts
> +        expect(consoleWarnSpy).toHaveBeenCalledTimes(2);
Isso aqui você vai descobrir com o tempo, mas um dos "problemas" de se escrever testes, é que com o tempo, a medida que o projeto avança, alguns testes começam a quebrar, sem que de fato o projeto em si contenha algum bug. Isso acontece quando a gente testa algumas coisas muito específicas.

Por exemplo, aqui vc testa o console.warn. Se no futuro, algum dev (que nem sabe da existencia desses testes) decide tirar o console.warn, o projeto vai continuar funcionando normal, compilando, e sem erros. Porém os testes vão falhar. E é ruim que isso aconteça, porque tira a confiança dos testes.

O mundo ideal é que os testes falham apenas quando de fato existe algum bug no código.

Tudo isso pra dizer que colocar testes em `console.warn` não costuma ser uma boa prática. Não precisa tirar se não quiser, pode deixar. Mas é só pra vc saber os trade-offs.

2024-11-22 18:13 UTC, Daymannovaes commented on frontend/tests/submit-button-integration.test.ts
> +        (vi.mocked(getConfiguration)).mockReturnValue(mockConfig);
boa! Legal que tu tentou criar um teste de integração. Eu raramente escrevo esse tipo de teste. Mas quando eu faço, eu evito AO MÁXIMO qualquer tipo de mock desnecessário (porque se eu mocko as dependências, eu deixo de testar a INTEGRAÇÃO deles, saca?).

Então se vc quiser manter o teste de integração, recomendo você tirar os mocks em splitText e getConfiguration, e deixar que elas sejam chamadas naturalmente (e mocka só as "pontas". Por exemplo, o html).

2024-12-03 13:33 UTC, gabrielttavares commented on frontend/src/utils/create-list-items.ts
> +    displayText.appendChild(ul);
Done

2024-12-03 16:00 UTC, gabrielttavares commented on frontend/tests/submit-button-integration.test.ts
> +        (vi.mocked(getConfiguration)).mockReturnValue(mockConfig);
Principais mudanças:

Remoção dos mocks de funções (splitText, getConfiguration) para testar a verdadeira integração
Adição de testes para tratamento de mensagens de erro e atualizações de exibição
Adição de teste para limpeza de mensagem de erro após entrada válida
Melhoria na legibilidade dos testes com padrões claros de arrange-act-assert

Foco agora está em como os componentes trabalham juntos, em vez de suas implementações internas.

2024-12-04 18:34 UTC, gabrielttavares commented on frontend/tests/initialize-color-picker.test.ts
> +        expect(consoleWarnSpy).toHaveBeenCalledTimes(2);
Principais mudanças feitas, então:
- Remove testes que verificavam chamadas de console.warn
- Testa se elementos faltantes são tratados sem quebrar a aplicação
- Verifica se os Pickers são criados apenas para elementos válidos

Testes mais resilientes pois só falharão quando houver problemas reais no comportamento do componente, não em
mudanças de implementação que não afetam sua funcionalidade.

2024-12-06 13:02 UTC, Daymannovaes approved these changes

2024-12-06 13:49 UTC, merged