Text Input and Submit Button Proper Executions
Daymannovaes/carousel-builder pull request #2
Opened 2024-09-26 23:19 UTC by gabrielttavares

- add a text field with a submit button and display the text on submit
- split text into list items (max 50 words or 300 chars)
- add char counter
- add charCount variable to fix condition bug
- final adjustments

2024-09-26 23:35 UTC, Daymannovaes requested changes
Boa, no geral ficou bom. Gostei dos nomes de varíaveis e da lógica. Corrige esses 3 pontos que comentei que fica perfeito.

Vou pedir dois bônus, que não precisa se achar muito difícil (a gente volta neles depois):

bonus 1:
- você definiu 100% do seu código dentro de uma função. Normal quando se está iniciando. Mas idealmente você vai separar as responsabilidades em diferentes funções.
- função 1: recebe como argumento uma string e retorna uma array de strings onde cada string tenha 50 palavras ou 300 caracteres
- função 2: recebe um array de strings e cria um `li` para cada item do array
- função geral: reage ao evento de click, chama a função 1, pega o retorno dela, depois chama a função 2


bonus 2:
- se tiver alguma palavra com mais de 300 caracteres mostra uma mensagem de erro

2024-09-26 23:35 UTC, Daymannovaes commented on src/index.js
> +    textInput.value = "";
do ponto de vista de experiência do usuário, não faz sentido limpar o campo depois que eu dei submit, pois eu posso querer editar o texto várias vezes antes de ficar confortável com a versão final.

2024-09-26 23:35 UTC, Daymannovaes commented on src/index.js
> +            currentItem = document.createElement("li");
um `li` deve sempre estar dentro de um `ol` ou `ul`, nunca pode estar flutuando.

2024-09-26 23:35 UTC, Daymannovaes commented on src/index.js
> +    charCounter.textContent = `Characters: ${textInput.value.length}`;
a gente nunca acessa o html dessa forma, diretamente pelo `id`. Quando a gente tá lendo um arquivo javascript, a gente sempre espera que determinada variável está definida no próprio arquivo. O arquivo tem que ser auto contido em si mesmo.

Portanto é uma boa prática vc definir `const charCounter = ...` usando o `getElementById` (ou o `querySelector`)

2024-09-27 01:59 UTC, gabrielttavares commented on src/index.js
> +    textInput.value = "";
retirado.

2024-09-27 01:59 UTC, gabrielttavares commented on src/index.js
> +            currentItem = document.createElement("li");
corrigido.

2024-09-27 01:59 UTC, gabrielttavares commented on src/index.js
> +    charCounter.textContent = `Characters: ${textInput.value.length}`;
definido usando getElementById.

2024-09-27 12:24 UTC, Daymannovaes approved these changes
nuh, ficou top demais. Parabéns pelo seu primeiro Pull Request em um projeto de verdade. Em breve estará rodando em produção pronto pro público usar.

Parabéns, você se tornou oficialmente um dev. De presente, toma aqui o selo oficial do dev secular:

![image](https://github.com/user-attachments/assets/41ffb8f1-0c96-4764-b4f8-e6aad635710f)

2024-09-27 17:02 UTC, merged